DROP TABLE IF EXISTS voucher_order;
DROP TABLE IF EXISTS seckill_voucher;
DROP TABLE IF EXISTS voucher;
DROP TABLE IF EXISTS follow;
DROP TABLE IF EXISTS blog;
DROP TABLE IF EXISTS shop;
DROP TABLE IF EXISTS shop_type;
DROP TABLE IF EXISTS users;
