ALTER TABLE users
 ADD COLUMN city VARCHAR(128) NOT NULL DEFAULT '',
 ADD COLUMN introduce VARCHAR(512) NOT NULL DEFAULT '',
 ADD COLUMN gender TINYINT UNSIGNED NOT NULL DEFAULT 0,
 ADD COLUMN birthday DATE NULL,
 ADD COLUMN credits INT UNSIGNED NOT NULL DEFAULT 0,
 ADD COLUMN level INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE blog ADD COLUMN images TEXT NULL;
